common/models/ShowTimesDetail.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "tbl_show_times_detail".
 *
 * @property integer $id
 * @property integer $cine_complex_id
 * @property integer $show_times_id
 * @property integer $screen_id
 * @property integer $movie_id
 * @property integer $playtime_id
 * @property integer $normal_seat_remaining
 * @property integer $vip_seat_remaining
 * @property integer $created_at
 * @property integer $created_by
 * @property integer $updated_at
 * @property integer $updated_by
 *
 * @property Booking[] $bookings
 * @property CinemaComplex $cineComplex
 * @property User $createdBy
 * @property Movie $movie
 * @property Playtime $playtime
 * @property Screen $screen
 * @property ShowTimes $showTimes
 * @property User $updatedBy
 */
class ShowTimesDetail extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%show_times_detail}}';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at', 'updated_at'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
            [
                'class' => BlameableBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_by', 'updated_by'],
                    ActiveRecord::EVENT_BEFORE_UPDATE => ['updated_by'],
                ],
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['cine_complex_id', 'show_times_id', 'screen_id', 'movie_id', 'playtime_id'], 'required'],
            [['cine_complex_id', 'show_times_id', 'screen_id', 'movie_id', 'playtime_id', 'normal_seat_remaining', 'vip_seat_remaining'], 'integer'],
            [['playtime_id'], 'unique', 'targetAttribute' => ['cine_complex_id', 'show_times_id', 'screen_id', 'playtime_id'], 'message' => 'This Show times has already been taken.'],
            [['cine_complex_id'], 'exist', 'skipOnError' => true, 'targetClass' => CinemaComplex::className(), 'targetAttribute' => ['cine_complex_id' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['movie_id'], 'exist', 'skipOnError' => true, 'targetClass' => Movie::className(), 'targetAttribute' => ['movie_id' => 'id']],
            [['playtime_id'], 'exist', 'skipOnError' => true, 'targetClass' => Playtime::className(), 'targetAttribute' => ['playtime_id' => 'id']],
            [['screen_id'], 'exist', 'skipOnError' => true, 'targetClass' => Screen::className(), 'targetAttribute' => ['screen_id' => 'id']],
            [['show_times_id'], 'exist', 'skipOnError' => true, 'targetClass' => ShowTimes::className(), 'targetAttribute' => ['show_times_id' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['updated_by' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'cine_complex_id' => 'CineComplex',
            'show_times_id' => 'Show Times',
            'screen_id' => 'Screen',
            'movie_id' => 'Movie',
            'playtime_id' => 'Playtime',
            'normal_seat_remaining' => 'Normal Seat',
            'vip_seat_remaining' => 'Vip Seat',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'updated_at' => 'Updated At',
            'updated_by' => 'Updated By',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBookings()
    {
        return $this->hasMany(Booking::className(), ['show_times_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCineComplex()
    {
        return $this->hasOne(CinemaComplex::className(), ['id' => 'cine_complex_id']);
    }
    public function getListCineComplex()
    {
        $list = CinemaComplex::find()->all();
        return ArrayHelper::map($list, 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'created_by']);
    }
    public function getUserCreate(){
        return $this->createdBy->full_name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMovie()
    {
        return $this->hasOne(Movie::className(), ['id' => 'movie_id']);
    }
    public function getListMovie()
    {
        $list = Movie::find()->all();
        return ArrayHelper::map($list, 'id', 'title');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlaytime()
    {
        return $this->hasOne(Playtime::className(), ['id' => 'playtime_id']);
    }
    public function getPlayTimeDetail()
    {
        return date('H:i', $this->playtime->start_time). ' - ' .date('H:i', $this->playtime->end_time);
    }
    public function getListPlaytime()
    {
        $list = Playtime::find()->select(['id','start_time', 'end_time'])->all();
        $listTemp = [];
        foreach ($list as $item):
            $listTemp[$item->id] = $this->formatTime($item->start_time). ' - ' .$this->formatTime($item->end_time);
        endforeach;
        return $listTemp;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getScreen()
    {
        return $this->hasOne(Screen::className(), ['id' => 'screen_id']);
    }
    public function getListScreen()
    {
        $list = Screen::find()->all();
        return ArrayHelper::map($list, 'id', 'name');
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShowTimes()
    {
        return $this->hasOne(ShowTimes::className(), ['id' => 'show_times_id']);
    }
    public function getShowTimesDate()
    {
        return $this->formatDate($this->showTimes->date);
    }
    public function getListShowTimes()
    {
        $list = ShowTimes::find()->all();
        $list = ArrayHelper::map($list, 'id', 'date');
        $listTemp = [];
        foreach ($list as $id => $date):
            $listTemp[$id] = $this->formatDate($date);
        endforeach;
        return $listTemp;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(User::className(), ['id' => 'updated_by']);
    }
    public function getUserUpdate(){
        return $this->updatedBy->full_name;
    }

    public function formatDateTime($timestamp){
        return date('d/m/Y h:i:s A', $timestamp);
    }

    public function formatDate($timestamp){
        return date('d/m/Y', $timestamp);
    }

    public function formatTime($timestamp){
        return date('H:i', $timestamp);
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert){
            // Update List seat to table booking_detail
            $listSeatByScreen = Seat::find()
                ->select('id')
                ->where(['screen_id' => $this->screen_id])
                ->all();
            $count = count($listSeatByScreen);
            $show_times_detail_id = $this->id;
            $listSeat = [];
            foreach ($listSeatByScreen as $key => $item):
                $listSeat[$key] = $item['id'];
            endforeach;

            for ($i = 0; $i < $count; $i++)
            {
                $model = new BookingDetail();
                $model->show_times_detail_id = $show_times_detail_id;
                $model->seat_id = $listSeat["$i"];
                $model->status = 0;
                if ($model->save(false)){

                }else{
                    echo '<pre>';
                    print_r($model->getErrors());die;
                }
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}

backend/controllers/ShowTimesDetailController.php
<?php

namespace backend\controllers;

use common\models\BookingDetail;
use common\models\Screen;
use common\models\Seat;
use Yii;
use common\models\ShowTimesDetail;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\bootstrap4\ActiveForm;

/**
 * ShowTimesDetailController implements the CRUD actions for ShowTimesDetail model.
 */
class ShowTimesDetailController extends Controller
{
    /**
     * Lists all ShowTimesDetail models.
     * @return mixed
     */
    public function actionIndex()
    {
        $model = new ShowTimesDetail();
        $dataProvider = new ActiveDataProvider([
            'query' => ShowTimesDetail::find(),
        ]);

        $dataProvider->pagination->pageSize = 5;

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'model' => $model
        ]);
    }

    /**
     * Displays a single ShowTimesDetail model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ShowTimesDetail model.
     * If creation is successful, the browser will be redirected to the 'view' slide.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ShowTimesDetail();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if($model->load(Yii::$app->request->post())){
            $screen_id = Yii::$app->request->post()["ShowTimesDetail"]['screen_id'];
            $screen = Screen::findOne(['id' => $screen_id]);
            $model->normal_seat_remaining = $screen->normal_seat_quantity;
            $model->vip_seat_remaining = $screen->vip_seat_quantity;
            if ($model->save())
                Yii::$app->session->setFlash('success', "Create Time ID: <b>".$model->id."</b> successful.");
            else
            {
                echo '<pre>';
                print_r($model->getErrors());die;
            }
                Yii::$app->session->setFlash('error', 'Error: '.print_r($model->getErrors()).'');
            return $this->redirect(['index']);
        }
        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ShowTimesDetail model.
     * If update is successful, the browser will be redirected to the 'view' slide.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post())) {
            $screen_id = Yii::$app->request->post()["ShowTimesDetail"]['screen_id'];
            $screen = Screen::findOne(['id' => $screen_id]);
            $model->normal_seat_remaining = $screen->normal_seat_quantity;
            $model->vip_seat_remaining = $screen->vip_seat_quantity;
            if ($model->save())
                Yii::$app->session->setFlash('success', "Update Time ID: <b>".$model->id."</b> successful.");
            else
                Yii::$app->session->setFlash('error', 'Error: ' . print_r($model->getErrors()));
            return $this->redirect(['index']);
        }
        return $this->renderAjax('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ShowTimesDetail model.
     * If deletion is successful, the browser will be redirected to the 'index' slide.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->addFlash('success', 'Delete this show times successful.');
        return $this->redirect(['index']);
    }

    public function actionSearchByCinemaComplex($complex_id){
        $query = new Query();
        $query ->select(['sc.id', 'sc.name'])
            ->from('{{%cinema_complex}} cc')
            ->join('inner join',
                '{{%screen}} sc',
                'cc.id = sc.cine_complex_id'
            )
            ->where(['cc.id' => $complex_id]);
        $query->createCommand();
        $data = $query->all();

        $listData = '<option value="">--- Choose Screen ---</option>';
        foreach ($data as $item):
            $listData .= '<option value="'.$item['id'].'">'.$item['name'].'</option>';
        endforeach;

        $this->asJson($listData);
    }

    /**
     * Finds the ShowTimesDetail model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ShowTimesDetail the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ShowTimesDetail::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested slide does not exist.');
        }
    }

    public function actionGetScreenById($id)
    {
        $screen_id = ShowTimesDetail::findOne(['id' => $id])->screen_id;
        echo $screen_id;
    }

    public function actionSearch($value = null)
    {
        if ($value == null):
            return $this->actionIndex();
        else:
            $dataProvider = new ActiveDataProvider([
                'query' => ShowTimesDetail::find()->where([
                    'OR',
                    ['like', 'cine_complex_id', $value],
                    ['like', 'FROM_UNIXTIME(`show_times_id`, "%d/%m/%Y")', $value],
                    ['like', 'screen_id', $value],
                    ['like', 'movie_id', $value],
                    ['like', 'FROM_UNIXTIME(`playtime_id`+3600, "%H:%i")', $value]
                ])
            ]);
        endif;

        $dataProvider->pagination->pageSize = 5;
        return $this->render('index',[
            'dataProvider' => $dataProvider,
        ]);
    }
}

frontend/controllers/ShowTimesDetailController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\ShowTimesDetail;
use frontend\models\ShowTimesDetailSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ShowTimesDetailController implements the CRUD actions for ShowTimesDetail model.
 */
class ShowTimesDetailController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ShowTimesDetail models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ShowTimesDetailSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 10;
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ShowTimesDetail model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }
}

backend/views/show-times-detail/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\ShowTimesDetail */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="show-times-detail-form">

    <?php $action = $model->isNewRecord ? 'create-form' : 'update-form' ?>
    <?php $form = ActiveForm::begin([
        'id' => $action,
        'enableAjaxValidation' => true,
    ]); ?>

    <?php
        if($action == 'update-form')
        {
            echo $form->field($model, 'id')->hiddenInput()->label(false);
        }
    ?>

    <?= $form->field($model, 'show_times_id')->dropDownList(
        $model->getListShowTimes(), [
            'prompt' => '--- Choose Date ---'
        ]
    ) ?>

    <?= $form->field($model, 'cine_complex_id')->dropDownList(
        $model->getListCineComplex(), [
            'prompt' => '--- Choose CineComplex ---'
        ]
    ) ?>

    <?= $form->field($model, 'screen_id')->dropDownList([
            'prompt' => '--- Choose Screen ---'
        ]
    ) ?>

    <?= $form->field($model, 'movie_id')->dropDownList(
        $model->getListMovie(), [
            'prompt' => '--- Choose Movie ---'
        ]
    ) ?>

    <?= $form->field($model, 'playtime_id')->dropDownList(
        $model->getListPlaytime(),[
            'prompt' => '--- Choose Playtime ---'
        ]
    ) ?>

    <div class="form-group d-flex justify-content-end">
        <?= Html::submitButton($model->isNewRecord ? '<i class="fas fa-save"></i> Create' : '<i class="fas fa-save"></i> Update', ['class' => $model->isNewRecord ? 'btn btn-success mr-2' : 'btn btn-primary mr-2']) ?>
        <?= Html::button('Close', ['class' => 'btn btn-secondary', 'data-dismiss' => 'modal']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$urlCineComplex = \yii\helpers\Url::to(['show-times-detail/search-by-cinema-complex']);
$this->registerJs(<<<JS
    $('#showtimesdetail-cine_complex_id').change(function() {
        let complex_id = $(this).val();
            let data = { complex_id: complex_id }
            $.ajax({ 
                url: '$urlCineComplex',
                method: 'GET',
                data: data,
                success: function(data) {
                    $('#showtimesdetail-screen_id').html(data);
                },
                error: function(xhr, ajaxOptions, thrownError){
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
    });
JS
    , $this::POS_READY);

if ($action == 'update-form'){
    $urlGetScreenId = \yii\helpers\Url::to(['show-times-detail/get-screen-by-id']);
    $this->registerJs(<<<JS
        let complex_id = $('#showtimesdetail-cine_complex_id').val();
        let data = { complex_id: complex_id }
        $.ajax({ 
            url: '$urlCineComplex',
            method: 'GET',
            data: data,
            success: function(data) {
                $('#showtimesdetail-screen_id').html(data);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
        
        let id = $('#showtimesdetail-id').val();
        let res = { id: id }
        $.ajax({ 
            url: '$urlGetScreenId',
            method: 'GET',
            data: res,
            success: function(res) {
                $('#showtimesdetail-screen_id').val(res);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
        
JS
        , $this::POS_READY);
}
?>

backend/views/show-times-detail/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap4\Modal;
use yii\bootstrap4\ActiveForm;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Show Times Details';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="inner-head">
    <?= Html::encode($this->title) ?>
</div>
<div class="inner-content">
    <div class="inner-top d-flex mb-3">
        <span class="title align-items-center">
            <img src="<?= Url::to(['images/bullet-room-list.png']) ?>" alt="bullet-show-times-detail-list" title="Show Times Detail List">Show Times Detail List
        </span>
        <div class="filter-data mt-1 ml-3">
            <div class="input-group search-data">
                <?php $form = ActiveForm::begin([
                    'enableClientValidation' => false,
                    'method' => 'GET',
                    'action' => Url::to(['show-times-detail/search']),
                    'options' => [
                        'class' => 'form-inline'
                    ]
                ]) ?>
                <?= Html::textInput('value', null, ['class' => 'form-control', 'placeholder' => 'Search']) ?>
                <div class="input-group-append">
                    <?= Html::submitButton('<i class="fas fa-search"></i>', ['class' => 'btn btn-outline-secondary btn-search']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="btn-create ml-auto">
            <?= Html::button('<i class="fas fa-plus-circle"></i> Create', ['value' => Url::To(['show-times-detail/create']),'class' => 'btn btn-primary modalButtonCreate']) ?>

            <?php
            Modal::begin([
                'title' => '<h5>Create New Show Times Detail</h5>',
                'id' => 'modal-create',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalCreateContent'></div>"
            ?>

            <?php Modal::end(); ?>

            <?php
            Modal::begin([
                'title' => '<h5>Update Show Times Detail</h5>',
                'id' => 'modal-update',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalUpdateContent'></div>"
            ?>
            <?php Modal::end(); ?>

            <?php
            Modal::begin([
                'title' => '<h5>Detail Show Times Detail</h5>',
                'id' => 'modal-view',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalViewContent'></div>"
            ?>
            <?php Modal::end(); ?>

        </div>
    </div>
    <div class="inner-detail position-relative pb-5">
        <?php Pjax::begin(); ?>
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'tableOptions' => ['class' => 'table table-bordered table-hover table-responsive-md'],
                'columns' => [
                    //['class' => 'yii\grid\SerialColumn'],
                    'id',
                    [
                        'attribute' => 'cine_complex_id',
                        'value' => 'cineComplex.name'
                    ],
                    [
                        'attribute' => 'show_times_id',
                        'value' => 'showTimesDate',

                    ],
                    [
                        'attribute' => 'screen_id',
                        'value' => 'screen.name'
                    ],
                    [
                        'attribute' => 'movie_id',
                        'value' => 'movie.title'
                    ],
                    [
                        'attribute' => 'playtime_id',
                        'value' => 'playTimeDetail'
                    ],
                    //'normal_seat_remaining',
                    //'vip_seat_remaining',
                    // 'created_at',
                    // 'created_by',
                    // 'updated_at',
                    // 'updated_by',

                    ['class' => 'yii\grid\ActionColumn',
                        'header' => 'Action',
                        'headerOptions' => [
                            'class' => 'text-center'
                        ],
                        'contentOptions' => [
                            'class' => 'text-center',
                            'style' => 'width:25%'
                        ],
                        'buttons' => [
                            'view' => function($url){
                                return Html::button('<i class="fas fa-eye"></i> View',[
                                    'class' => 'btn btn-success btn-xs modalButtonView',
                                    'value' => $url,
                                ]);
                            },
                            'update' => function($url){
                                return Html::button('<i class="fas fa-edit"></i> Edit',[
                                    'value' => $url,
                                    'class' => 'btn btn-primary btn-xs modalButtonUpdate',
                                ]);
                            },
                            'delete' => function($url, $model){
                                return Html::a('<i class="fas fa-trash-alt"></i> Delete', $url, [
                                    'class' => 'btn btn-danger btn-xs',
                                    'data-confirm' => 'Bạn có muốn xóa lịch chiếu có ID = '.$model->id.' không?',
                                    'data-method' => 'POST'
                                ]);
                            }
                        ]
                    ],
                ],
                'pager' => [
                    'class' => 'justinvoelker\separatedpager\LinkPager',
                    'prevPageLabel' => '<span class="fas fa-angle-left"></span>',
                    'nextPageLabel' => '<span class="fas fa-angle-right"></span>',
                    'maxButtonCount' => 7,
                    'options' => ['class' => 'pagination justify-content-end mr-3 position-absolute'],
                ]
            ]); ?>
        <?php Pjax::end(); ?>
    </div>
</div>

backend/views/show-times-detail/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\ShowTimesDetail */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Show Times Details', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="show-times-detail-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'cineComplex.name',
            'showTimesDate',
            'screen.name',
            'movie.title',
            'playTimeDetail',
            'normal_seat_remaining',
            'vip_seat_remaining',
            [
                'attribute' => 'created_at',
                'value' => $model->formatDateTime($model->created_at)
            ],
            [
                'attribute' => 'userCreate',
                'label' => 'Created by'
            ],
            [
                'attribute' => 'updated_at',
                'value' => $model->formatDateTime($model->updated_at)
            ],
            [
                'attribute' => 'userUpdate',
                'label' => 'Updated by'
            ]
        ],
    ]) ?>

</div>