backend/controllers/BookingController.php
<?php

namespace backend\controllers;

use common\models\BookingDetail;
use common\models\SeatCategory;
use Yii;
use common\models\Booking;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\bootstrap4\ActiveForm;
use common\models\ShowTimesDetail;
use common\models\Seat;

ob_start();

/**
 * BookingController implements the CRUD actions for Booking model.
 */
class BookingController extends Controller
{
    /**
     * Lists all Booking models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Booking::find(),
        ]);

        $dataProvider->pagination->pageSize = 5;

        return $this->render('index', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Displays a single Booking model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Booking model.
     * If creation is successful, the browser will be redirected to the 'view' slide.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Booking();
        $showTimes = new ShowTimesDetail();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if($model->load(Yii::$app->request->post())){
            if ($model->save())
                Yii::$app->session->setFlash('success', "Create booking ID: <b>$model->id</b> successful.");
            else
                Yii::$app->session->setFlash('error', 'Not create <b>' . $model->id . '</b>');
            return $this->redirect(['index']);
        }
        return $this->renderAjax('_form', [
            'model' => $model,
            'showTimes' => $showTimes
        ]);
    }

    /**
     * Updates an existing Booking model.
     * If update is successful, the browser will be redirected to the 'view' slide.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $showTimes = new ShowTimesDetail();
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save())
                Yii::$app->session->setFlash('success', "Update booking ID: <b>$model->id</b> successful.");
            else
                Yii::$app->session->setFlash('error', 'Error: ' . print_r($model->getErrors()));
            return $this->redirect(['index']);
        }
        return $this->renderAjax('_form', [
            'model' => $model,
            'showTimes' => $showTimes
        ]);
    }

    public function actionSearchByCinemaComplex($complex_id)
    {
        $query = new Query();
        $query ->select(['std.show_times_id as id', 'FROM_UNIXTIME(st.date, "%d/%m/%Y") date'])
            ->from('{{%show_times_detail}} std')
            ->join('inner join',
                '{{%show_times}} st',
                'st.id = std.show_times_id'
            )
            ->where(['std.cine_complex_id' => $complex_id])
            ->groupBy('std.show_times_id');
        $query->createCommand();
        $data = $query->all();

        $listData = '<option value="">--- Choose Date ---</option>';
        foreach ($data as $item):
            $listData .= '<option value="'.$item['id'].'">'.$item['date'].'</option>';
        endforeach;

        $this->asJson($listData);
    }

    public function actionSearchByShowTimes($complex_id, $show_times_id)
    {
        $query = new Query();
        $query ->select(['std.screen_id as id', 'sc.name as screen_name'])
            ->from('{{%show_times_detail}} std')
            ->join('inner join',
                '{{%screen}} sc',
                'sc.id = std.screen_id'
            )
            ->where(['std.cine_complex_id' => $complex_id])
            ->andWhere(['std.show_times_id' => $show_times_id])
            ->groupBy('std.screen_id');
        $query->createCommand();
        $data = $query->all();

        $listData = '<option value="">--- Choose Screen ---</option>';
        foreach ($data as $item):
            $listData .= '<option value="'.$item['id'].'">'.$item['screen_name'].'</option>';
        endforeach;

        $this->asJson($listData);
    }

    public function actionSearchByScreen($complex_id, $show_times_id, $screen_id)
    {
        $query = new Query();
        $query ->select(['std.movie_id as id', 'mv.title as movie_title'])
            ->from('{{%show_times_detail}} std')
            ->join('inner join',
                '{{%movie}} mv',
                'mv.id = std.movie_id'
            )
            ->where(['std.cine_complex_id' => $complex_id])
            ->andWhere(['std.show_times_id' => $show_times_id])
            ->andWhere(['std.screen_id' => $screen_id])
            ->groupBy('std.movie_id');
        $query->createCommand();
        $data = $query->all();

        $listData = '<option value="">--- Choose Movie ---</option>';
        foreach ($data as $item):
            $listData .= '<option value="'.$item['id'].'">'.$item['movie_title'].'</option>';
        endforeach;

        $this->asJson($listData);
    }

    public function actionSearchByMovie($complex_id, $show_times_id, $screen_id, $movie_id)
    {
        $query = new Query();
        $query ->select(['std.playtime_id as id', 'FROM_UNIXTIME(pt.start_time+3600, "%H:%i") start_time', 'FROM_UNIXTIME(pt.end_time+3600, "%H:%i") end_time'])
            ->from('{{%show_times_detail}} std')
            ->join('inner join',
                '{{%playtime}} pt',
                'pt.id = std.playtime_id'
            )
            ->where(['std.cine_complex_id' => $complex_id])
            ->andWhere(['std.show_times_id' => $show_times_id])
            ->andWhere(['std.screen_id' => $screen_id])
            ->andWhere(['std.movie_id' => $movie_id])
            ->groupBy('std.movie_id');
        $query->createCommand();
        $data = $query->all();

        $listData = '<option value="">--- Choose Playtime ---</option>';
        foreach ($data as $item):
            $listData .= '<option value="'.$item['id'].'">'.$item['start_time'].'-'.$item['end_time'].'</option>';
        endforeach;

        $this->asJson($listData);
    }

    public function actionGetIdShowTimesDetail($complex_id, $show_times_id, $screen_id, $movie_id, $playtime_id)
    {
        $idShowTimes = ShowTimesDetail::findOne([
            'cine_complex_id' => $complex_id,
            'show_times_id' => $show_times_id,
            'screen_id' => $screen_id,
            'movie_id' => $movie_id,
            'playtime_id' => $playtime_id
        ])->id;

        echo '<input type="hidden" id="getShowTimesId" value="'.$idShowTimes.'">';

        $booking = new Booking();
        $listSeat = $booking->getListSeatById($idShowTimes);
        foreach ($listSeat as $seatLine => $items):
            echo '<div class="d-flex bd-highlight mb-2 justify-content-center">
            <ul class="list-seat-code pl-0">
                <li class="mr-5 text-center">'.$seatLine.'</li>
                <li class="p-0">
                    <ul class="sub-list p-0 text-center">
                ';
                    $statusSeat = '';
                    foreach ($items as $id => $seatCode):
                        $status = BookingDetail::findOne(['show_times_detail_id' => $idShowTimes, 'seat_id' => $id])->status;
                        ($status == 1) ? $statusSeat = 'booked' : $statusSeat = '';
                        $catId = Seat::findOne(['id' => $id])->cat_id;
                        $catSeat = strtolower(SeatCategory::findOne(['id' => $catId])->title);
                        echo '<li class="'.$catSeat.' '.$statusSeat.'" value="'.$id.'">'.$seatLine.$seatCode.'</li>';
                    endforeach;
            echo '
                    </ul>
                </li>
            </ul>
        </div>
        <!-- End list seat -->';
        endforeach;

        echo "<script>
                $(document).ready(function() {
                      // Checked and choose Seat
                      $('ul.sub-list li').click(function() {
                            $(this).toggleClass('checked');
                      });
                      $('.btn-SeatChecked').click(function() {
                            let hClass = $('ul.sub-list li').hasClass('checked');
                            if(hClass){
                                let ArrValue = [];
                                $('li.checked').each(function() {
                                    let value = $(this).val();
                                    ArrValue.push( value );
                                });
                                $('#booking-seat_code').val(ArrValue);
                                $('#seatChecked').val(ArrValue);
                                $('#chooseSeat').modal('hide');
                            }
                            $('.btn-delete-seat').removeAttr('disabled');
                            $('.btn-choose-seat').attr('disabled',true);
                      });
                });
            </script>";
    }

    /**
     * Deletes an existing Booking model.
     * If deletion is successful, the browser will be redirected to the 'index' slide.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->addFlash('success', 'Delete successful.');

backend/views/booking/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */
/* @var $form yii\widgets\ActiveForm */

?>

<div class="booking-form">
    <?php $action = $model->isNewRecord ? 'create' : 'update' ?>
    <?php $form = ActiveForm::begin([
        'id' => $action,
        'enableAjaxValidation' => true
    ]); ?>

    <?= $form->field($model, 'full_name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'phone_number')->textInput(['maxlength' => true]) ?>

    <?php
        if($action == 'create')
        {
            echo $form->field($model, 'complex_name')->dropDownList(
                $showTimes->getListCineComplex(),
                [
                    'prompt' => '--- Choose CinemaComplex ---'
                ]);
            echo $form->field($model, 'show_date')->dropDownList([
                'prompt' => '--- Choose Date ---'
            ]);
            echo $form->field($model, 'screen_name')->dropDownList([
                'prompt' => '--- Choose Screen ---',

            ]);
            echo $form->field($model, 'movie_title')->dropDownList([
                'prompt' => '--- Choose Movie ---'
            ]);
            echo $form->field($model, 'show_time')->dropDownList([
                'prompt' => '--- Choose Time ---'
            ]);
        }
        else
        {
            echo $form->field($model, 'show_times_detail_id')->hiddenInput()->label(false);

            //$model->complex_name = \common\models\CinemaComplex::findOne(['name' => $model->complex_name])->id;
            echo  $form->field($model, 'complex_name')->dropDownList(
                $showTimes->getListCineComplex()
            );

            //$model->show_date = \common\models\ShowTimes::findOne(['date'=> $model->show_date])->id;
            echo $form->field($model, 'show_date')->dropDownList(
                $showTimes->getListShowTimes()
            );

            //$model->screen_name = \common\models\Screen::findOne(['name' => $model->screen_name])->id;
            echo $form->field($model, 'screen_name')->dropDownList(
                $showTimes->getListScreen()
            );

            //$model->movie_title = \common\models\Movie::findOne(['title' => $model->movie_title])->id;
            echo $form->field($model, 'movie_title')->dropDownList(
                $showTimes->getListMovie()
            );

            echo $form->field($model, 'show_time')->dropDownList(
                $showTimes->getListPlaytime()
            );
        }
    ?>


    <?= $form->field($model, 'seat_code',['options' => ['class' => 'mb-1']])->textInput(['readonly'=>true]) ?>
    <!-- Button trigger modal choose seat -->
    <button type="button" class="btn btn-primary btn-xs mb-2 btn-choose-seat" data-toggle="modal" data-target="#chooseSeat" <?php if($action=='update') echo 'disabled'; ?>>
        Choose Seats
    </button>
    <button type="button" id="btn-delete-seat" class="btn btn-danger btn-xs mb-2 btn-delete-seat" <?php if($action=='create') echo 'disabled'; ?>>
        Clean Seats
    </button>

    <?= $form->field($model, 'price')->input('number',['readonly' => true]) ?>

    <?= $form->field($model, 'normal_ticket')->hiddenInput(['readonly' => true])->label(false) ?>

    <?= $form->field($model, 'vip_ticket')->hiddenInput(['readonly' => true])->label(false) ?>

<!--    echo $form->field($model, 'status')->radioList([0 => 'Unpaid', 1 => 'Paid']) -->

    <?= $form->field($model, 'description')->textarea(['maxlength' => true]) ?>

    <input type="hidden" id="seatChecked" name="seatChecked">
    <input type="hidden" id="showTimesId" name="showTimesId">

    <div class="form-group d-flex justify-content-end">
        <?= Html::submitButton($model->isNewRecord ? '<i class="fas fa-save"></i> Create' : '<i class="fas fa-save"></i> Update', ['class' => $model->isNewRecord ? 'btn btn-success mr-2' : 'btn btn-primary mr-2']) ?>
        <?= Html::button('Close', ['class' => 'btn btn-secondary' , 'data-dismiss' => 'modal']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
$urlCineComplex = Url::to(['booking/search-by-cinema-complex']);
$urlShowTimes = Url::to(['booking/search-by-show-times']);
$urlScreen = Url::to(['booking/search-by-screen']);
$urlMovie = Url::to(['booking/search-by-movie']);
$urlGetPrice = Url::to(['booking/price-by-seat-id']);
$urlGetIdShowTimesDetail = Url::to(['booking/get-id-show-times-detail']);
$urlGetDataUpdate = Url::to(['booking/get-data-update']);
$this->registerJs(<<<JS
    // Clean data screen when open form
    $('#seat-control').html('<p class="text-center text-danger">Không có dữ liệu</p>');
    $('#btn-delete-seat').click(function() {
        $('#booking-seat_code').val(null);
        $('#booking-price').val(null);
        $('.btn-choose-seat').removeAttr('disabled');
        $(this).attr('disabled', true);
       
        let hClass = $('ul.sub-list li').hasClass('checked');
        if (hClass){
            $('ul.sub-list li').removeClass('checked');
        } 
    });

    // Event change on complex_name
    $('#booking-complex_name').change(function() {
        let complex_id = $(this).val();
        let data = { complex_id: complex_id }
        $.ajax({ 
            url: '$urlCineComplex',
            method: 'GET',
            data: data,
            success: function(data) {
                $('#booking-show_date').html(data);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
    });
    // Event change on show date
    $('#booking-show_date').change(function() {
        let show_times_id = $(this).val();
        let complex_id = $('#booking-complex_name').val();
        let data = { show_times_id: show_times_id, complex_id: complex_id }
        $.ajax({
            url: '$urlShowTimes',
            method: 'GET',
            data: data,
            success: function(data) {
                $('#booking-screen_name').html(data);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
    });
    // Event change on screen
    $('#booking-screen_name').change(function() {
        let screen_id = $(this).val();
        let complex_id = $('#booking-complex_name').val();
        let show_times_id = $('#booking-show_date').val();
        let data = { 
            show_times_id: show_times_id, 
            complex_id: complex_id, 
            screen_id: screen_id 
        }
        $.ajax({ 
            url: '$urlScreen',
            method: 'GET',
            data: data,
            success: function(data) {
                $('#booking-movie_title').html(data);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
    });
    // Event change on movie
    $('#booking-movie_title').change(function() {
        let movie_id = $(this).val();
        let complex_id = $('#booking-complex_name').val();
        let show_times_id = $('#booking-show_date').val();
        let screen_id = $('#booking-screen_name').val();
        let data = { 
            show_times_id: show_times_id, 
            complex_id: complex_id, 
            screen_id: screen_id,
            movie_id: movie_id
        }
        $.ajax({ 
            url: '$urlMovie',
            method: 'GET',
            data: data,
            success: function(data) {
                $('#booking-show_time').html(data);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
    });
    
    // Event change show time
    $('#booking-show_time').change(function() {
        let playtime_id = $(this).val();
        let complex_id = $('#booking-complex_name').val();
        let show_times_id = $('#booking-show_date').val();
        let screen_id = $('#booking-screen_name').val();
        let movie_id =  $('#booking-movie_title').val();
        let data = { 
            show_times_id: show_times_id, 
            complex_id: complex_id, 
            screen_id: screen_id,
            movie_id: movie_id,
            playtime_id: playtime_id
        }
        $.ajax({ 
            url: '$urlGetIdShowTimesDetail',
            method: 'GET',
            data: data,
            success: function(data) {
                // Load data seat in screen to modal
                $('#seat-control').html(data);
                
                let id = $('#getShowTimesId').val();
                $('#showTimesId').val(id);
            },
            error: function(xhr, ajaxOptions, thrownError){
                alert(xhr.status);
                alert(thrownError);
            }
        });
    });
    
    // Checked and choose Seat
    $('#chooseSeat').on('hide.bs.modal', function() {
        let hClass = $('ul.sub-list li').hasClass('checked');
        if(hClass){
            let listSeat = $('#booking-seat_code').val();
            let data = { listSeat: listSeat }
            $.ajax({ 
                url: '$urlGetPrice',
                method: 'GET',
                data: data,
                success: function(data) {
                    $('#booking-seat_code').val(data['listSeatLine']);
                    $('#booking-price').val(data['listData']['price_total']);
                    $('#booking-normal_ticket').val(data['listData']['Normal']);
                    $('#booking-vip_ticket').val(data['listData']['Vip']);
                },
                error: function(xhr, ajaxOptions, thrownError){
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
        }
    })
JS
    , $this::POS_READY);
if($action == 'update'){
    $this->registerJs(<<<JS
        getDateUpdate();
        $('.modalButtonUpdate').click(function() {
            getDateUpdate();
        });
        function getDateUpdate() {
            let show_times_detail_id = $('#booking-show_times_detail_id').val();
            let data = {
                show_times_detail_id: show_times_detail_id
            }
            $.ajax({ 
                url: '$urlGetDataUpdate',
                method: 'GET',
                data: data,
                success: function(data) {
                    $('#booking-complex_name').val(data['dataUpdate'].cine_complex_id);
                    $('#booking-show_date').val(data['dataUpdate'].show_times_id);
                    $('#booking-screen_name').val(data['dataUpdate'].screen_id);
                    $('#booking-movie_title').val(data['dataUpdate'].movie_id);
                    $('#booking-show_time').val(data['dataUpdate'].playtime_id);
                },
                error: function(xhr, ajaxOptions, thrownError){
                    alert(xhr.status);
                    alert(thrownError);
                }
            });
    
            $("#booking-show_time").trigger("change");
            $('#btn-delete-seat').click(function() {
                $('#booking-seat_code').val(null);
                $('#booking-price').val(null);
                $('.btn-choose-seat').removeAttr('disabled');
                $(this).attr('disabled', true);
               
                let hClass = $('ul.sub-list li').hasClass('checked');
                if (hClass){
                    $('ul.sub-list li').removeClass('checked');
                } 
            });
        }
     
JS
        , $this::POS_READY);
}
?>

backend/views/booking/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use yii\bootstrap4\Modal;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Bookings';
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="inner-head">
    <?= Html::encode($this->title) ?>
</div>
<div class="inner-content">
    <div class="inner-top d-flex mb-3">
        <span class="title align-items-center">
            <img src="<?= Url::to(['images/bullet-room-list.png']) ?>" alt="bullet-booking-list"
                 title="Booking List">Booking List
        </span>
        <div class="filter-data mt-1 ml-3">
            <div class="input-group search-data">
                <?php $form = ActiveForm::begin([
                    'enableClientValidation' => false,
                    'method' => 'GET',
                    'action' => Url::to(['booking/search']),
                    'options' => [
                        'class' => 'form-inline'
                    ]
                ]) ?>
                <?= Html::textInput('value', null, ['class' => 'form-control', 'placeholder' => 'Search']) ?>
                <div class="input-group-append">
                    <?= Html::submitButton('<i class="fas fa-search"></i>', ['class' => 'btn btn-outline-secondary btn-search']) ?>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
        <div class="btn-create ml-auto">
            <?= Html::button('<i class="fas fa-plus-circle"></i> Create', ['value' => Url::To(['booking/create']),'class' => 'btn btn-primary modalButtonCreate']) ?>
            <?php
            Modal::begin([
                'title' => '<h5>Create New Booking</h5>',
                'id' => 'modal-create',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalCreateContent'></div>"
            ?>
            <?php Modal::end(); ?>

            <?php
            Modal::begin([
                'title' => '<h5>Update Booking</h5>',
                'id' => 'modal-update',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalUpdateContent'></div>"
            ?>
            <?php Modal::end(); ?>

            <?php
            Modal::begin([
                'title' => '<h5>Detail Booking</h5>',
                'id' => 'modal-view',
                'size' => 'modal-md'
            ]);
            echo "<div id='modalViewContent'></div>"
            ?>
            <?php Modal::end(); ?>
        </div>
    </div>
    <div class="inner-detail table-responsive-md">
        <?php Pjax::begin(); ?>
        <?= GridView::widget([
            'tableOptions' => [
                'class' => 'table table-bordered table-hover table-responsive-md'
            ],
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                //'id',
                'full_name',
                'phone_number',
                'seat_code',
                'complex_name',
                //'screen_name',
                //'movie_title',
                // 'show_date',
                // 'show_time',
                // 'normal_ticket',
                // 'vip_ticket',
                [
                    'attribute' => 'price',
                    'value' => function($model){
                        return $model->formatNumber($model->price, null);
                    }
                ],
                // 'description',
                [
                    'attribute' => 'status',
                    'content' => function($model){
                        if ($model->status == 1)
                            return '<span class="badge badge-pill badge-success">Paid</span>';
                        return '<span class="badge badge-pill badge-danger">Unpaid</span>';
                    }
                ],
                // 'show_times_id:datetime',
                // 'user_id',
                // 'created_at',
                // 'updated_at',

                ['class' => 'yii\grid\ActionColumn',
                    'header' => 'Action',
                    'headerOptions' => [
                        'class' => 'text-center'
                    ],
                    'contentOptions' => [
                        'class' => 'text-center'
                    ],
                    'buttons' => [
                        'view' => function($url){
                            return Html::button('<i class="fas fa-eye"></i> View',[
                                'class' => 'btn btn-success btn-xs modalButtonView',
                                'value' => $url,
                            ]);
                        },
                        'update' => function($url){
                            return Html::button('<i class="fas fa-edit"></i> Edit',[
                                'value' => $url,
                                'class' => 'btn btn-primary btn-xs modalButtonUpdate',
                            ]);
                        },
                        'delete' => function($url, $model){
                            return Html::a('<i class="fas fa-trash-alt"></i> Delete', $url, [
                                'class' => 'btn btn-danger btn-xs',
                                'data-confirm' => 'Bạn có muốn xóa bảng ghi đặt vé của '.$model->full_name.' không?',
                                'data-method' => 'POST'
                            ]);
                        }
                    ]
                ],
            ],
            'pager' => [
                'class' => 'justinvoelker\separatedpager\LinkPager',
                'prevPageLabel' => '<span class="fas fa-angle-left"></span>',
                'nextPageLabel' => '<span class="fas fa-angle-right"></span>',
                'maxButtonCount' => 7,
                'options' => ['class' => 'pagination justify-content-end mr-3 position-absolute'],
            ]
        ]); ?>
        <?php Pjax::end(); ?>
    </div>

    <!-- Modal Choose Seat -->
    <div class="modal fade" id="chooseSeat" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body position-relative">
                    <div class="border text-white text-center" style="background: #8D1B5B; font-size: 20px; margin-bottom: 80px">
                        Màn hình
                    </div>
                    <div class="note-status-seat position-absolute d-flex align-items-center">
                        <span class="bg-represent" style="background: #FF5900"></span> <span class="ml-1">Seat line</span>
                        <span class="bg-represent ml-3" style="background: #f5f5f5"></span> <span class="ml-1">Seat booked</span>
                        <span class="bg-represent ml-3" style="background: #B24D80"></span> <span class="ml-1">Seat normal</span>
                        <span class="bg-represent ml-3" style="background: #e4b301"></span> <span class="ml-1">Seat vip</span>
                    </div>
                    <div id="seat-control">
                        <p class="text-center text-danger">Không có dữ liệu</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary btn-SeatChecked">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</div>

backend/views/booking/view.php
<?php

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Booking */

//$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Bookings', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="booking-view">

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'full_name',
            'phone_number',
            'seat_code',
            'complex_name',
            'screen_name',
            'movie_title',
            'show_date',
            'show_time',
            'normal_ticket',
            'vip_ticket',
            [
                'attribute' => 'price',
                'value' => function($model){
                    return $model->formatNumber($model->price, null);
                }
            ],
            'description',
            [
                'attribute' => 'status',
                'value' => function($model){
                    if ($model->status == 1)
                        return 'Paid';
                    return 'Unpaid';
                }
            ],
            //'show_times_detail_id',
            [
                'attribute' => 'created_at',
                'value' => $model->formatDateTime($model->created_at)
            ],
            [
                'attribute' => 'updated_at',
                'value' => $model->formatDateTime($model->updated_at)
            ],
        ],
    ]) ?>

</div>